config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'comments/create'

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :toggle
      end
      collection do
        patch :clear_all
        patch :complete_all
        delete :delete_all
      end
    end
  end
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "todo_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 140 }
  validates :author, presence: true, length: { maximum: 25 }
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list

  validates :content, presence: true

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  has_many :todo_items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable, # disable registration
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:destroy]

  def create
    @comment = Comment.new(comment_params)
    @comment.save
    redirect_to root_path(anchor: 'comments')
  end

  def destroy
    @comment.destroy
    redirect_to root_path(anchor: 'pagination')
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :author)
  end
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item,
                except: [:create, :complete_all, :clear_all, :delete_all]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to todo_list_path(@todo_list, anchor: 'add')
  end

  def edit 
  end

  def update
    if @todo_item.update_attributes(todo_item_params)
      redirect_to @todo_list
    end
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = "Todo List item was deleted"
    else
      flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to todo_list_path(@todo_list, anchor: 'anchor')
  end

  def toggle
    if @todo_item.completed_at.nil?
      @todo_item.update_attribute(:completed_at, Time.now)
      redirect_to todo_list_path(@todo_list, anchor: @todo_item.id)
    else
      @todo_item.update_attribute(:completed_at, nil)
      redirect_to todo_list_path(@todo_list, anchor: @todo_item.id)
    end
  end

  def complete_all
    @todo_list.todo_items.each do |item|
      item.update_attribute(:completed_at, Time.now)
    end
    redirect_to todo_list_path(@todo_list, anchor: 'add')
  end

  def clear_all
    @todo_list.todo_items.each do |item|
      item.update_attribute(:completed_at, nil)
    end
    redirect_to todo_list_path(@todo_list, anchor: 'add')
  end

  def delete_all
    @todo_list.todo_items.each do |item|
      item.delete
    end
    redirect_to todo_list_path(@todo_list)
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params[:todo_item].permit(:content, :category)
  end
end

app/controllers/todo_lists_controller.rb
require 'will_paginate/array'

class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all

    @comments = Comment.all.sort_by {
      # sort by newest first
      |item| [item.created_at]}.reverse!.paginate(page: params[:page],
                                                  per_page: 10)
    @comment = Comment.new
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/comments/_all.html.erb
<div class="comments" id="comments">
  <h1 class="comments title">Comments</h1>
  
  <%= render 'comments/form' %>

  <div id="pagination"></div>
  <%= will_paginate @comments,:params => {:anchor => "pagination"}%>
    <%= render @comments %>
  <%= will_paginate @comments,:params => {:anchor => "pagination"}%>
</div>

app/views/comments/_comment.html.erb
<div class="comment">
  <p class="body"><%= comment.body %></p>
  <p class="author"><%= comment.author %></p>
  <p class="date">
    <%= comment.created_at.localtime.strftime("%b %-d") %>
    - <%= comment.created_at.localtime.strftime("%I:%M %p") %>
  </p>
  <%= link_to comment,
              method: :delete,
              class: 'delete',
              data: { 
                confirm: "Delete '#{comment.body}' by #{comment.author}?"
              } do %>
    <i class="fa fa-trash"> Delete</i>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, autocomplete: 'off',
                           placeholder: 'New Comment' %>
  </div>

  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author, id: 'author'%>
  </div>

  <div class="actions">
    <%= f.submit 'Post' %>
  </div>
<% end %>

<script>
  // clear text on click
  $('#author').focus(function() {
    $('#author').val('');
  });

  // replace blank w/ default value
  // - this runs fast enough to replace even if user submits
  //   the form while focusing the author text field!
  $('#author').focusout(function() {
    if ($('#author').val() === '') {
      $('#author').val('anon');
    }
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>List App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0"/> 
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href='//fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
</head>

<body>
  <header>
    <% if !notice.nil? || !alert.nil? %>
      <div class="alert">
        <%= notice %>
        <%= alert %>
      </div>
    <% end %>

    <nav>
      <%= link_to todo_lists_path do %>
        <i class="fa fa-home fa-3x"></i>
      <% end %>
    </nav>
  </header>
  <div class="container">

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>

  <%= f.text_field :content, placeholder: "New Item", autocomplete: "off" %>
  <%= f.submit 'Add' , id: "add" %>
  <%= f.text_field :category, placeholder: "Category" %>
<% end %>

app/views/todo_items/_todo_item.html.erb
<% if todo_item.completed? %>
	<div class="tdrow completed">
		<div class="complete">
			<%= link_to edit_todo_list_todo_item_path(@todo_list, todo_item.id) do %>
				<i style="opacity: 0.2;" class="fa fa-cog"></i>
			<% end %>
		</div>
		<%= link_to toggle_todo_list_todo_item_path(@todo_list, todo_item.id),
			 						method: :patch do %>
			<div class="todo_item" id="<%= todo_item.id %>">
				<p style="opacity: 0.2;">
					<strike>
						<% if !todo_item.category.nil? %>
							<% if !todo_item.category.empty? %>
								<strong><%= todo_item.category %>:</strong>
							<% end %>
						<% end %>
						<%= todo_item.content %>
					</strike>
				</p>
			</div>
		<% end %>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), 
									method: :delete do %>
				<i style="opacity: 0.2;" class="fa fa-trash"></i>
			<% end %>
		</div>
	</div>


<!-- not completed -->	
<% else %>
	<div class="tdrow uncompleted">
		<div class="complete">
			<%= link_to edit_todo_list_todo_item_path(@todo_list, todo_item.id) do %>
				<i class="fa fa-cog"></i>
			<% end %>
		</div>
		<%= link_to toggle_todo_list_todo_item_path(@todo_list, todo_item.id),
									method: :patch do %>
			<div class="todo_item" id="<%= todo_item.id %>">
				<p>
					<% if !todo_item.category.nil? %>
						<% if !todo_item.category.empty? %>
							<strong><%= todo_item.category %>:</strong>
						<% end %>
					<% end %>
					<%= todo_item.content %>
				</p>
			</div>
		<% end %>
		<div class="trash">
			<%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), 
									method: :delete do %>
				<i class="fa fa-trash"></i>
			<% end %>
		</div>
	</div>
<% end %>

app/views/todo_items/edit.html.erb
<h2 class="todo_list_title">Edit Item</h2>
<hr />

<div class="todo_items_wrapper">

  <%= render @todo_item %>

  <div id="form">
    <%= form_for([@todo_list, @todo_item]) do |f| %>
      <%= f.text_field :content,
                       value: @todo_item.content,
                       autocomplete: "off" %>
      <%= f.submit 'Save', method: :patch %>
      <%= f.text_field :category, placeholder: "Category" %>
    <% end %>


  </div>
</div>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
      <% todo_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, autocomplete: 'off' %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, autocomplete: 'off' %>
  </div>

  <div class="actions">
    <%= f.submit 'Update' %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Edit Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
 <!-- <div class="container"> in index.html.erb-->

   <!-- todolists section -->
  <h1 class="comments title">ToDo Lists</h1>
  <% @todo_lists.each do |todo_list| %>
    <div class="index_row clearfix">
      <h2 class="todo_list_title"><%= link_to todo_list.title, todo_list %></h2>
      <p class="todo_list_sub_title"><%= todo_list.description %></p>
    </div>
  <% end %>

  <div class="links">
    <%= link_to "New Todo List", new_todo_list_path %>
  </div>

</div>
<nav>
  <% if user_signed_in? %>
    <%= link_to destroy_user_session_path, method: :delete do %>
      <i class="fa fa-sign-out fa-3x"></i>
    <% end %>
  <% end %>
</nav>
<!-- this is a hack to split containers special for home page.
     so i don't have to div every page -->
<div class="container">

  <!-- comments section -->
  <%= render 'comments/all' %>
<!-- </div> in index.html.erb

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">New Todo List</h1>

<div class="forms">
	<%= render 'form' %>
</div>

<div class="links">
	<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>

<div class="todo_items_wrapper">
	<%= render @todo_list.todo_items.sort_by {
    |item| [item.category ? 0 : 1, item.category || 0,
            item.completed_at ? 0 : 1, item.completed_at || 0]} %>
	<div id="form">
		<%= render "todo_items/form" %>
	</div>
</div>

<div class="links">
  <%= link_to 'Check All',
              complete_all_todo_list_todo_items_path(@todo_list),
              method: :patch %> |
  <%= link_to 'Clear All',
              clear_all_todo_list_todo_items_path(@todo_list),
              method: :patch %> |
  <%= link_to 'Delete All',
              delete_all_todo_list_todo_items_path(@todo_list),
              method: :delete,
              data: { 
                confirm: "Delete all items in '#{@todo_list.title}'?" 
              } %>
  <hr />
	<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
	<%= link_to 'Delete',
              todo_list_path(@todo_list),
              method: :delete,
              data: { confirm: "Delete '#{@todo_list.title}'?" } %> |
  <%= link_to 'Back to Lists', todo_lists_path %>
</div>
<script>
  // set anchor tag for redirects
  $(document).ready(function() {
    if ($('.uncompleted').length > 0) {
      $('.uncompleted')[0].id = "anchor"
    }
    else {
      $('.time')[0].id = "anchor"
    }
  });
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>